<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Http;
use Laravel\Lumen\Routing\Controller;

class PlaStgController extends Controller
{
    public function migrate()
    {
        $pos = 1;

        $gameList = $this->gameList();

        foreach ($gameList as $game) {
            $requestData[] = [
                'providerCode' => 'PLA',
                'providerName' => 'PLAYTECH SLOTS',
                'gameCode' => $game[1],
                'gameName' => $game[0],
                'position' => $pos,
                'type' => 'slot',
                'rtp' => $game[2],
                'imageUrl' => '-',
                'imageAlt' => $game[0],
            ];

            $pos++;
        }

        dd($requestData);

        // foreach ($requestData as $data) {
        //     $response = Http::withHeaders([
        //         'Authorization' => 'Bearer ' . env('BEARER_TOKEN_PROD')
        //         // ])->post(env('ADD_GAME_API_PROD'), $data);
        //     ])->post('dummyApi.com', $data);

        //     Log::info(json_encode([
        //         'request' => $data,
        //         'response' => $response->body()
        //     ]));
        // }
    }

    private function gameList()
    {
        return [
            ["28 Mansions", "gpas_28dman_pop", "96.19%"],
            ["A Night Out", "hb", "97.06%"],
            ["Absolutely Mammoth!™", "gpas_amammoth_pop", "96.49%"],
            ["Age of Egypt", "agoeg", "97.05%"],
            ["Alohawaii: Cash Collect™", "gpas_alohacc_pop", "95.87%"],
            ["Anaconda Uncoiled™", "gpas_auncoil_pop", "95.94%"],
            ["Anaconda Wild 2™", "gpas_awild2_pop", "96.47%"],
            ["Anaconda Wild™", "anwild", "95.48%"],
            ["Archer", "gpas_archer_pop", "96.77%"],
            ["Arowanas Luck", "gpas_aluck_pop", "97.52%"],
            ["Asian Fantasy", "asfa", "96.02%"],
            ["Atlantis Cash Collect™", "gpas_ccskingofa_pop", "96.25%"],
            ["Aztec Expedition™ Thundershots™", "gpas_aexpedition_pop", "95.50%"],
            ["Azteca Bonus Lines™", "gpas_azboli_pop", "94.93%"],
            ["Bai Shi", "bs", "95.99%"],
            ["Bee Frenzy Thundershots™", "gpas_bfrenzy_pop", "96.14%"],
            ["Bermuda Triangle", "bt", "96.73%"],
            ["Berry Berry Bonanza", "gpas_berrybon_pop", "95.99%"],
            ["Better Wilds™", "gpas_betwilds_pop", "96.42%"],
            ["Big Shots™", "bigsh", "96.10%"],
            ["Blazing Bells™", "gpas_bbells_pop", "96.37%"],
            ["Blue Wizard", "gpas_bwizard_pop", "96.50%"],
            ["Bonus Bears", "bob", "95.17%"],
            ["Bonus Train Bandits", "gpas_btbandit_pop", "96.12%"],
            ["Book of Kings", "gpas_boking_pop", "96.64%"],
            ["Breakout Bob", "gpas_bbob_pop", "96.52%"],
            ["Buccaneer Blast", "gpas_pblast_pop", "96.15%"],
            ["Buckle Up", "bup", "95.80%"],
            ["Buffalo Blitz", "gpas_bblitz_pop", "95.96%"],
            ["Buffalo Blitz II™", "gpas_bblitz2_pop", "95.96%"],
            ["Caishen Ways", "gpas_cways_pop", "96.91%"],
            ["Captain's Treasure", "gpas_captres_pop", "97.06%"],
            ["Cascading Cave", "gpas_ccave_pop", "95.83%"],
            ["Casino Charms", "gpas_cascharms_pop", "96.06%"],
            ["Cat Queen", "catqc", "93.60%"],
            ["Chaoji 888", "chao", "96.47%"],
            ["Chili Eruption Thundershots™ ", "gpas_ceruption_pop", "96.17%"],
            ["Chilli Xtreme™", "gpas_cxtreme_pop", "95.23%"],
            ["Chinese Kitchen", "cm", "96.92%"],
            ["Crazy 7", "c7", "96.98%"],
            ["Curse of Anubis™", "gpas_soanubis_pop", "96.01%"],
            ["Da Vinci’s Vault", "dvncv", "92.06%-94.04%"],
            ["Desert Treasure", "mobdt", "97.05%"],
            ["Devil Wilds™", "gpas_devwilds_pop", "95.50%"],
            ["Diamond Rise™", "gpas_drise_pop", "95.96%"],
            ["Divine 9™", "gpas_divine_pop", "95.90%"],
            ["Dolphin Reef", "gpas_dreef_pop", "95.23%"],
            ["Dragon Bond", "gpas_dbond_pop", "96.85%"],
            ["Dragon Champions", "drgch", "95.12%"],
            ["Dragon Chi", "gpas_dragonchi_pop", "96.87%"],
            ["Dragon Spark", "gpas_dsparks_pop", "96.31%"],
            ["Dragons Hall™", "gpas_dhall_pop", "95.35%"],
            ["Easter Surprise", "eas", "97.05%"],
            ["Egyptian Emeralds™", "gpas_eemeralds_pop", "96.36%"],
            ["Eliminators", "gpas_eliminators_pop", "95.76%"],
            ["Epic Ape", "gpas_eape_pop", "95.96%"],
            ["Eternal Lady", "gpas_elady_pop", "96.50%"],
            ["Eye of Anubis", "gpas_sscarab_pop", "95.76%"],
            ["Fairground Fortunes Ghost Train", "ashfgf", "94.06%"],
            ["Fat Choy Choy Sun™", "gpas_fatchoy_pop", "96.62%"],
            ["Fei Long Zai Tian", "gpas_flztian_pop", "96.03%"],
            ["Feng Kuang Ma Jiang", "fkmj", "96.06%"],
            ["Fire 4: Cash Collect Quattro™ A1", "gpas_f4ccd_pop", "94.80%"],
            ["Fire Blaze Golden: Buccaneer Bells™", "gpas_fbgbb_pop", "96.48%"],
            ["Fire Blaze Golden™ Amazing Factory™", "gpas_afactory_pop", "96.50%"],
            ["Fire Blaze Quattro: Celtic Charm™", "gpas_qccharm_pop", "95.83%"],
            ["Fire Blaze: Adventure Trail", "gpas_atrail_pop", "96.64%"],
            ["Fire Blaze: Blue Wizard™ Megaways™", "gpas_mgbwizard_pop", "96.47%"],
            ["Fire Blaze: Green Wizard™", "gpas_gwizard_pop", "95.90%"],
            ["Fire Blaze: Jinns Moon", "gpas_jmoon_pop", "96.58%"],
            ["Fire Blaze: Pearls Pearls Pearls", "gpas_pppearls_pop", "96.50%"],
            ["Fire Blaze: Red Wizard", "gpas_rwizard_pop", "96.49%"],
            ["Fire Blaze: River Empress", "gpas_rempress_pop", "96.50%"],
            ["Fire Blaze: Sisters Gift", "gpas_sgift_pop", "96.47%"],
            ["Fire Blaze: Toltec Blocks™", "gpas_qctoblo_pop", "95.92%"],
            ["Fire Blaze™ Golden: Tundra Wolf™", "gpas_twolf_pop", "96.46%"],
            ["Fire Blaze™: Fire Fighter™", "gpas_ffighter_pop", "95.92%"],
            ["Fishin' Bonanza™", "gpas_ffever_pop", "96.51%"],
            ["Football Rules!", "fbr", "97.06%"],
            ["Football! Cash Collect™", "gpas_focashco_pop", "94.91%"],
            ["Forest Prince™", "gpas_fprince_pop", "95.84%"],
            ["Fortune Day", "fday", "97.51%"],
            ["Fortune Lions", "frtln", "96.63%"],
            ["Fortunes of the Fox (Foxy Fortune)", "fxf", "95.11%"],
            ["Frogs Gift", "gpas_fgift_pop", "96.76%"],
            ["Full Moon: White Panda™", "gpas_wpanda_pop", "95.90%"],
            ["Full Moon: Wild Track™", "gpas_wtrack_pop", "95.93%"],
            ["Funky Monkey", "fm", "97.15%"],
            ["Gaelic Luck", "popc", "97.06%"],
            ["Galactic Streak™", "galst", "95.95%"],
            ["Geisha Story", "ges", "95.48%"],
            ["Gem Heat", "gemheat", "92.05%"],
            ["Gem Queen", "gemq", "96.06%"],
            ["Glorious Guardians™", "gpas_gguardians_pop", "96.49%"],
            ["Gold Hit: Dragon Bonanza™", "gpas_goldhit3_pop", "95.50%"],
            ["Gold Hit: Shrine Of Anubis™", "gpas_goldhit2_pop", "95.80%"],
            ["Gold Hit™: O’Reilly’s Riches", "gpas_bcash_pop", "95.21%"],
            ["Gold Pile Tigers Pride", "gpas_tfortune_pop", "96.47%"],
            ["Gold Pile: New Years Gold", "gpas_gpnyg_pop", "96.46%"],
            ["Gold Pile: Orangutan!", "gpas_gporang_pop", "96.45%"],
            ["Gold Pile: Toltec Treasure", "gpas_ttreasure_pop", "96.46%"],
            ["Golden Macaque", "gpas_gmacaque_pop", "96.73%"],
            ["Golden Tour", "gpas_goltour_pop", "97.71%"],
            ["Golden Ways", "gpas_buddhaways_pop", "96.92%"],
            ["Grand Junction : Golden Guns™", "gpas_ggun_pop", "96.41%"],
            ["Grand Junction: Mountain Express™", "gpas_mountexp_pop", "96.51%"],
            ["Great Blue™", "gpas_gblue_pop", "96.03%"],
            ["Hainan Ice", "gpas_hice_pop", "96.82%"],
            ["Halloween Fortune", "hlf", "97.06%"],
            ["Halloween Fortune II", "hlf2", "94.99%"],
            ["Haunted House", "hh", "96.71%"],
            ["Heart of the Frontier", "ashhof", "96.09%"],
            ["Heavenly Ruler", "heavru", "96.32%"],
            ["Heroes Arrow™", "gpas_harrow_pop", "96.38%"],
            ["Highway Kings", "gpas_highkings_pop", "97.05%"],
            ["Hit Bar: Gold™", "gpas_hitbargl_pop", "95.61%"],
            ["Hit Bar™", "gpas_fmhitbar_pop", "96.00%"],
            ["Hologram Wilds", "hwilds", "95.97%"],
            ["Hot Gems™", "gpas_hgems_pop", "95.99%"],
            ["Hot Gems™ Xtreme", "gpas_hgextreme_pop", "95.81%"],
            ["Hot KTV", "hotktv", "95.56%"],
            ["Ice Cave", "gpas_icave_pop", "96.04% - 96.12%"],
            ["Irish Luck", "irl", "94.25%"],
            ["Jane Jones in Book of Kings 2", "gpas_nalight_pop", "96.50%"],
            ["Jin Qian Wa", "jqw", "96.96%"],
            ["Jinfu Long", "gpas_jflong_pop", "96.51%"],
            ["JinfuXingyun", "gpas_xjinfu_pop", "96.49%"],
            ["Joker Rush™", "gpas_jrush_pop", "96.00%"],
            ["Juego De La Oca", "jdlo", "95.08%"],
            ["Jungle Giants", "jnglg", "95.06%"],
            ["Jurassic Island 2™", "gpas_jisland2_pop", "95.70%"],
            ["Koi Harmony™", "gpas_koihar_pop", "96.47%"],
            ["Legacy of the Wild", "gpas_lotwild_pop", "96.10%"],
            ["Legacy of the Wild 2™", "gpas_lotwild2_pop", "96.36%"],
            ["Legend of Hydra™", "gpas_hydra_pop", "96.56%"],
            ["Lie Yan Zuan Shi™", "ght_a", "94.99%"],
            ["Lock & Hit: Red Knight™", "gpas_monreelsa1_pop", "95.47%"],
            ["Lockdown Loot™", "gpas_pbreak_pop", "95.63%"],
            ["Long Long Long", "longlong", "96.31%"],
            ["Lotto Madness", "lm", "97.06%"],
            ["Lovefool™", "gpas_scupid_pop", "96.32%"],
            ["Lucky Emeralds™", "gpas_lemeralds_pop", "95.74%"],
            ["Luminous Life", "lumli", "94.44%"],
            ["Magical Stacks", "mgstk", "95.03%"],
            ["Maji Wilds", "mwilds", "95.25%"],
            ["Mayan Blocks™", "gpas_mblocks_pop", "95.36%"],
            ["Mega Fire Blaze: Emperor of Rome™", "gpas_eofrome_pop", "94.91%"],
            ["Mega Fire Blaze: Khonsu God of Moon™", "gpas_kgomoon_pop", "96.49%"],
            ["Mega Fire Blaze: Piggies And The Bank™", "gpas_engage_pop", "95.38%"],
            ["Mega Fire Blaze™ Wild Pistolero™", "gpas_wpisto_pop", "95.96%"],
            ["Mega Fire Blaze™: Big Circus!™", "gpas_bcircus_pop", "96.37%"],
            ["Mega Fire Blaze™: Legacy of the Tiger™", "gpas_lottiger_pop", "96.59%"],
            ["Midnight Wilds", "gpas_mwilds_pop", "95.00%"],
            ["Mighty Hat : Lamp of Gold™", "gpas_gwish_pop", "96.24%"],
            ["Mighty Hat : Mine O'Mine™", "gpas_grush_pop", "96.24%"],
            ["Mighty Hat : Mystic Tales™", "gpas_mforest_pop", "95.66%"],
            ["Miss Fortune", "mfrt", "95.03%"],
            ["Monkey and Rat™", "gpas_marat_pop", "97.52%"],
            ["Monster Multipliers™", "gpas_sking_pop", "95.70%"],
            ["Mr. Cashback", "mcb", "95.37%"],
            ["Murder Mystery", "murder", "96.53%"],
            ["Neptune’s™ Kingdom", "nk", "97.19%"],
            ["New Year's Bonanza", "gpas_nyslot_pop", "95.99%"],
            ["Ni Shu Shen Me", "gpas_nsshen_pop", "96.86%"],
            ["Ox Riches", "gpas_strongox_pop", "96.93%"],
            ["Panda Luck", "gpas_pluck_pop", "96.91%"],
            ["Panther Moon", "pmn", "95.17%"],
            ["Panther Pays", "gpas_panthpays_pop", "96.26%"],
            ["Penguin Vacation", "pgv", "94.25%"],
            ["Pharaoh's Daughter", "gpas_scqueen_pop", "96.50%"],
            ["Pharaoh's Secrets", "pst", "94.00%"],
            ["Pigeons From Space", "gpas_pigeonfs_pop", "95.97%"],
            ["Piggies and the Wolf", "paw", "92.10%"],
            ["Plenty O'Fortune™ ", "gpas_pffortune_pop", "91.95%"],
            ["Power Zones™: Ishtar", "gpas_ishtar_pop", "95.52%"],
            ["Power Zones™: Thunder Birds", "gpas_tbirds_pop", "96.42%"],
            ["Pumpkin Bonanza", "gpas_pumpkinb_pop", "95.51%"],
            ["Pyramid Valley™: Power Zones™", "gpas_pstrike_pop", "94.39%"],
            ["Qin's Empire : Caishen's Temple", "gpas_ctemple_pop", "95.36%"],
            ["Qin's Empire : Celestial Guardians™", "gpas_cguard_pop", "96.46%"],
            ["Queen of Wands", "qnw", "97.30%"],
            ["Quest West", "gpas_mquest_pop", "96.96%"],
            ["Ready To Blow: Thundershots™", "gpas_retoblow_pop", "95.61%"],
            ["Record Riches", "gpas_rriches_pop", "97.45%"],
            ["Retro Rush", "gpas_rrider_pop", "96.10%"],
            ["Ri Ri Jin Cai", "ririjc", "97.51%"],
            ["Rogues Draw™", "gpas_rogue_pop", "96.00%"],
            ["Rome & Glory", "rng2", "94.36%"],
            ["Royal Respin Deluxe", "rrd", "95.11%"],
            ["Sacred Stones", "scrdstns", "96.15%"],
            ["Safari Heat", "gpas_safarih_pop", "96.15%"],
            ["Sahara Riches MegaWays™: Cash Collect™", "gpas_mgccsahara_pop", "94.88%"],
            ["Sahara Riches™: Cash Collect™", "gpas_ccsahara_pop", "95.67%"],
            ["Sakura Fortune™powered by Rarestone™", "gpas_sfortune_pop", "96.53%"],
            ["Santa Surprise", "ssp", "97.05%"],
            ["Savage Jungle", "gpas_sjungle_pop", "96.54%"],
            ["Secrets of the Amazon", "samz", "95.30%"],
            ["Sherlock Mystery", "shmst", "94.09%"],
            ["Shield of Rome™ ", "gpas_sorome_pop", "95.20%"],
            ["Sinbad's Golden Voyage", "gpas_sgvoyage_pop", "97.00%"],
            ["Si Xiang", "sx", "96.00%"],
            ["Silent Samurai", "sis", "95.77%"],
            ["Silver Bullet", "sib", "95.44%"],
            ["Silver Bullet Bandit: Cash Collect™", "gpas_sbullet_pop", "95.44%"],
            ["Sky Queen", "gpas_squeen_pop", "96.58%"],
            ["Sorcerer's Guild of Magic", "gpas_sgomagic_pop", "96.09%"],
            ["Stallion Strike", "gpas_sstrike_pop", "96.27%"],
            ["Starmada Exiles", "gpas_sexiles_pop", "96.15%"],
            ["Stars Ablaze", "gpas_starsablaze_pop", "95.50%"],
            ["Stars Awakening", "strsawk", "95.93%"],
            ["Thai Paradise", "tpd2", "94.36%"],
            ["The Riches of Don Quixote™", "donq", "94.99%"],
            ["Tiger Claw", "tigc", "95.96%"],
            ["Tiger Stacks", "gpas_tstacks_pop", "96.52%"],
            ["Tiger Turtle Dragon Phoenix", "gpas_tigertdp_pop", "96.94%"],
            ["Tip Top Totems", "gpas_tttotems_pop", "96.56%"],
            ["Toads Gift", "gpas_tgift_pop", "96.76%"],
            ["Treasures of the Lamps", "totl", "95.15%"],
            ["Triple Monkey", "trpmnk", "97.00%"],
            ["Triple Stop Mermaids Find", "gpas_merfind_pop", "95.48%"],
            ["True Love", "trl", "94.35%"],
            ["Tsai Shen's Gift", "gpas_tsgift_pop", "96.50%"],
            ["Ugga Bugga", "ub", "98.74%"],
            ["Vacation Station", "er", "96.93%"],
            ["Vacation Station Deluxe", "vcstd", "96.93%"],
            ["Vampire Princess of Darkness", "gpas_vampirep_pop", "95.50%"],
            ["Ways of the Phoenix™", "wotp", "96.00%"],
            ["Wheels of Flame™", "gpas_wofire1_pop", "95.51%"],
            ["White King", "whk", "90.05%"],
            ["White King II™", "whk2", "91.40%"],
            ["Wild Lava", "gpas_wlava_pop", "96.47%"],
            ["Wild Linx™", "gpas_wlinx_pop", "96.49%"],
            ["Wild West Wilds", "gpas_wwd_pop", "96.14%"],
            ["Witches: Cash Collect™", "gpas_cchfortune_pop", "95.67%"],
            ["WOLVES WOLVES WOLVES", "www", "94.08%"],
            ["Wu Long ™ ", "wlg", "94.13%"],
            ["Wushu Punch™", "gpas_wpunch_pop", "95.99%"],
            ["Yu Tu Jin Cai Cash Collect™", "gpas_rabbitcash_pop", "94.91%"],
            ["Yun Cong Long", "yclong", "95.99%"],
            ["Zhao Cai Jin Bao", "zcjb", "95.99%"],
            ["Zhao Cai Jin Bao 2", "gpas_zcjbao2_pop", "95.26%"],
            ["Zhao Cai Tong Zi", "zctz", "97.01%"],
            ["Zodiac Charms", "gpas_zcharms_pop", "96.46%"],
            ["Azteca: Сash Сollect™", "gpas_aztecw_pop", "95.43%"],
            ["Rich Roll: Lust for Gold!™", "gpas_rrlustforg_pop", "94.90%"],
            ["Lucky Gift: Cash Collect™", "gpas_lgcc_pop", "95.59%"],
            ["Mega Fire Blaze: 3 Wizards™", "gpas_3wizards_pop", "95.83% - 95.96%"],
            ["Gold Hit: O'Reilly's Charms™ FB", "gpas_orwifefb_pop", "95.66% - 95.67%"],
            ["The Great Genie™", "gpas_gegenie_pop", "95.44%"],
            ["Veils Of Venice™", "gpas_venemasks_pop", "95.73% - 95.78%"],
            ["OINK OINK OINK™", "gpas_oink_pop", "95.91%"],
            ["Macabra Linx™", "gpas_mabralinx_pop", "95.88% - 95.92%"],
            ["Leprechaun's Luck - Cash Collect™ MEGAWAYS™", "gpas_lluckmcc_pop", "95.38%"],
            ["Panther Moon: Bonus Lines™", "gpas_pmoonbl_pop", "95.54%"],
            ["Mega Fire Blaze: Dwarves and Goblins™", "gpas_mfbdag_pop", "95.71%"],
            ["Gold Trio™", "gpas_gtfb_pop", "95.90%"],
            ["Feng Shui Flip™", "gpas_fsflip_pop", "95.48%"],
            ["Elephant Riches™", "gpas_elphrich_pop", "93.48% - 93.49%"],
            ["Wolves! Cash Collect & Link™", "gpas_wolcc_pop", "95.57%"],
            ["Candy Roll™", "gpas_sweroll_pop", "95.38% - 95.48%"],
        ];
    }
}
