<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Http;
use Laravel\Lumen\Routing\Controller;

class SabProdController extends Controller
{
    public function migrate()
    {
        // $pos = 1;
        // $betTypeList = $this->betType1();
        // $pos = 51;
        // $betTypeList = $this->betType2();
        // $pos = 101;
        // $betTypeList = $this->betType3();
        // $pos = 151;
        // $betTypeList = $this->betType4();
        // $pos = 201;
        // $betTypeList = $this->betType5();
        // $pos = 251;
        // $betTypeList = $this->betType6();
        // $pos = 301;
        // $betTypeList = $this->betType7();
        // $pos = 351;
        // $betTypeList = $this->betType8();
        // $pos = 401;
        // $betTypeList = $this->betType9();
        // $pos = 451;
        // $betTypeList = $this->betType10();
        // $pos = 501;
        // $betTypeList = $this->betType11();
        // $pos = 551;
        // $betTypeList = $this->betType12();
        // $pos = 601;
        // $betTypeList = $this->betType13();
        // $pos = 651;
        // $betTypeList = $this->betType14();
        // $pos = 701;
        // $betTypeList = $this->betType15();
        // $pos = 751;
        // $betTypeList = $this->betType16();
        // $pos = 801;
        // $betTypeList = $this->betType17();
        // $pos = 851;
        // $betTypeList = $this->betType18();
        // $pos = 901;
        // $betTypeList = $this->betType19();
        $pos = 951;
        $betTypeList = $this->betType20();

        $requestData = [];
        foreach ($betTypeList as $betTypeID => $betTypeName) {
            $requestData[] = [
                'providerCode' => 'SAB',
                'providerName' => 'SABA Sportsbook',
                'gameCode' => (string) $betTypeID,
                'gameName' => $betTypeName,
                'position' => $pos,
                'type' => $betTypeName,
                'rtp' => '0',
                'imageUrl' => '-',
                'imageAlt' => $betTypeName,
            ];

            $pos++;
        }

        dd($requestData);

        // foreach ($requestData as $data) {
        //     // $response = Http::withHeaders([
        //     //     'Authorization' => 'Bearer ' . env('BEARER_TOKEN_PROD')
        //     // // ])->post(env('ADD_GAME_API_PROD'), $data);
        //     // ])->post('dummyApi', $data);


        //     Log::info(json_encode([
        //         'request' => $data,
        //         'response' => $response->body()
        //     ]));
        // }

        dd('Inserted Games~');
    }

    private function betType1()
    {
        return [
            1 => "Handicap",
            2 => "Odd/Even",
            3 => "Over/Under",
            4 => "Correct Score",
            5 => "FT.1X2",
            6 => "Total Goal",
            7 => "1H Handicap",
            8 => "1H Over/Under",
            9 => "Mix Parlay",
            10 => "Outright",
            11 => "Total Corners",
            12 => "1H Odd/Even",
            13 => "Clean Sheet",
            14 => "First Goal/Last Goal",
            15 => "1H 1X2",
            16 => "HT/FT",
            17 => "2H Handicap",
            18 => "2H Over/Under",
            19 => "Substitutes",
            20 => "Moneyline",
            21 => "1H Moneyline",
            22 => "Next Goal",
            23 => "Next Corner",
            24 => "Double Chance",
            25 => "Draw No Bet",
            26 => "Both/One/Neither Team To Score",
            27 => "To Win To Nil",
            28 => "3-Way Handicap",
            29 => "System Parlay",
            30 => "1H Correct Score",
            31 => "Win",
            32 => "Place",
            33 => "Win/Place",
            38 => "Single Match Parlay",
            41 => "Win.UK Tote",
            42 => "Place.UK Tote",
            43 => "Win/Place.UK Tote",
            51 => "5 min O/U",
            52 => "15 min O/U",
            53 => "30 min O/U",
            54 => "45 min O/U",
            55 => "60 min O/U",
            56 => "End of day O/U",
            61 => "5 min OE",
            62 => "15 min OE",
            63 => "30 min OE",
            64 => "45 min OE",
            65 => "60 min OE",
            66 => "End of day OE",
            71 => "Casino Games",
        ];
    }

    private function betType2()
    {
        return [
            72 => "Casino Progressive Bonus",
            73 => " Bingo",
            81 => "1st Ball O/U",
            82 => "Last Ball O/U",
            83 => "1st Ball O/E",
            84 => "Last Ball O/E",
            85 => "Over/Under",
            86 => "Odd/Even",
            87 => "Next High/Low",
            88 => "Warrior",
            89 => "Next Combo",
            90 => "Number Wheel",
            91 => "Next Red/Blue",
            121 => "Home No Bet",
            122 => "Away No Bet",
            123 => "Draw/No Draw",
            124 => "FT.1X2 HDP",
            125 => "1H 1X2 HDP",
            126 => "1H Total Goal",
            127 => "1H First Goal/Last Goal",
            128 => "HT/FT Odd/Even",
            129 => "Exact 1H Goal",
            130 => "Exact Goal",
            131 => "Home Team Total Goal",
            132 => "Away Team Total Goal",
            133 => "Home To Win Both Halves",
            134 => "Away To Win Both Halves",
            135 => "Penalty Shootout",
            136 => "1H Home Team Odd/Even",
            137 => "Home Team Odd/Even",
            138 => "1H Away Team Odd/Even",
            139 => "Away Team Odd/Even",
            140 => "Highest Scoring Half",
            141 => "Highest Scoring Half Home Team",
            142 => "Highest Scoring Half Away Team",
            143 => "1H Result/Total Goals",
            144 => "Result/Total Goals",
            145 => "Both Teams To Score",
            146 => "2H Both Teams To Score",
            147 => "Home To Score In Both Halves",
            148 => "Away To Score In Both Halves",
            149 => "Home To Win Either Half",
            150 => "Away To Win Either Half",
            151 => "1H Double Chance",
            152 => "Half Time/Full Time Correct Score",
            153 => "Game Handicap",
            154 => "Set X Winner",
            155 => "Set x Game Handicap",
            156 => "Set x Total Game Over/Under",
            157 => "Odd/Even (3rd)",
        ];
    }

    private function betType3()
    {
        return [
            158 => "Correct Score",
            159 => "Exact Total Goals",
            160 => "Next Goal (3rd)",
            161 => "Exact Home Team Goals",
            162 => "Exact Away Team Goals",
            163 => "Result/Total Goals (3rd)",
            164 => "Extra Time Next Goal",
            165 => "Extra Time 1H Correct Score",
            166 => "Extra Time Correct Score",
            167 => "Extra Time 1H 1X2",
            168 => "Who Advances To Next Round",
            169 => "Next Goal Time",
            170 => "Teams To Score",
            171 => "Winning Margin",
            172 => "Result And First Team To Score",
            173 => "Extra Time Yes/No",
            174 => "Extra Time And Goal",
            175 => "Match Decided Method",
            176 => "First Ten Minutes 1X2",
            177 => "2H 1X2",
            178 => "2H Over/Under (3rd)",
            179 => "Exact 1H Goals (3rd)",
            180 => "1H Next Goal",
            181 => "1H Exact Home Team Goals",
            182 => "1H Exact Away Team Goals",
            183 => "2H Handicap (3rd)",
            184 => "2H Odd/Even",
            185 => "2H Draw No Bet",
            186 => "2H Double Chance",
            187 => "Exact 2H Goals (3rd)",
            188 => "1H Both Teams To Score",
            189 => "Both Halves Over 1.5 Yes/No",
            190 => "Both Halves Under 1.5 Yes/No",
            191 => "1H Draw No Bet",
            192 => "First Goal Specific Time (10 min)",
            193 => "First Goal Specific Time (15 min)",
            194 => "Corners Odd/Even",
            195 => "Home Team Exact Corners",
            196 => "Away Team Exact Corners",
            197 => "Home Team Total Corners Over/Under",
            198 => "Away Team Total Corners Over/Under",
            199 => "Total Corners (3rd)",
            200 => "1H Home Team Exact Corners",
            201 => "1H Away Team Exact Corners",
            202 => "1H Total Corners",
            203 => "1H Corners Odd/Even",
            204 => "1H Home Corner Over/Under",
            205 => "1H Away Corner Over/Under",
            206 => "First Corner",
            207 => "1H First Corner",
        ];
    }

    private function betType4()
    {
        return [
            208 => "Last Corner",
            209 => "1H Last Corner",
            210 => "Player Sent Off",
            211 => "1H Player Sent Off",
            212 => "Home Team Player Sent Off",
            213 => "1H Home Team Player Sent Off",
            214 => "Away Team Player Sent Off",
            215 => "1H Away Team Player Sent Off",
            216 => "Goal Scorer - Anytime",
            217 => "Goal Scorer - First",
            218 => "FT. Point HDP",
            219 => "Set X Points Handicap",
            220 => "Set X Total Points Over/Under",
            221 => "Next 1 Minute",
            222 => "Next 5 Minutes",
            223 => "What will happen first in next 1 minute",
            224 => "What will happen first in next 5 minutes",
            225 => "Next 1 Minute Set Piece",
            226 => "Which combination will happen first in next 1 min",
            227 => "Which combination will happen first in next 5 mins",
            228 => "SABA OU Time Machine",
            229 => "SABA HDP Time Machine",
            237 => "5408",
            301 => "% Handicap",
            302 => "% Over/Under",
            303 => "1H % Handicap",
            304 => "1H % Over/Under",
            375 => "Home Penalty Shootout Combo (First 5)",
            376 => "Penalty Shootout Combo (First 10)",
            381 => "Away Penalty Shootout - Round X",
            382 => "Home Penalty Shootout - Round X",
            383 => "Penalty Shootout Woodwork - Round X",
            384 => "Penalty Shootout Both/One/Neither - Round X",
            385 => "Penalty Shootout 1X2 - Round X",
            386 => "Away Penalty Shootout Over/Under (First 10)",
            387 => "Home Penalty Shootout Over/Under (First 10)",
            388 => "Away Penalty Shootout Over/Under (Final Result)",
            389 => "Home Penalty Shootout Over/Under (Final Result)",
            390 => "Penalty Shootout to Go to Sudden Death",
            391 => "Penalty Shootout Exact Total Goals (First 10)",
            392 => "Penalty Shootout Correct Score",
            393 => "Penalty Shootout Odd/Even (First 10)",
            394 => "Penalty Shootout Odd/Even (Final Result)",
            395 => "Extra Time Next Goal Method",
            396 => "Extra Time Next Goal (own)",
            397 => "Extra Time Winning Margin",
            398 => "Extra Time Double Chance",
            399 => "Extra Time Correct Score (own)",
            400 => "Extra Time Odd/Even",
            401 => "Home Team Over/Under",
        ];
    }

    private function betType5()
    {
        return [
            402 => "Away Team Over/Under",
            403 => "1H Home Team Over/Under",
            404 => "1H Away Team Over/Under",
            405 => "2H Correct Score",
            406 => "Exact Total Goals (own)",
            407 => "Exact Home Team Goals (own)",
            408 => "Winning Margin (own)",
            409 => "Exact Away Team Goals (own)",
            410 => "1H Double Chance (own)",
            411 => "1H Draw No Bet (own)",
            412 => "Exact 1H Goals",
            413 => "Correct Score (AOS)",
            414 => "1H Correct Score (AOS)",
            415 => "Result and First Team To Score (own)",
            416 => "Half Time/Full Time Correct Score (AOS)",
            417 => "Both Teams To Score/Result",
            418 => "Both Teams To Score/Total Goals",
            419 => "Which Half First Goal",
            420 => "Home Team Which Half First Goal",
            421 => "Away Team Which Half First Goal",
            422 => "First Team 2 Goals",
            423 => "First Team 3 Goals",
            424 => "First Goal Method",
            425 => "To Win From Behind",
            426 => "1H Winning Margin",
            427 => "1H Both Teams To Score (own)",
            428 => "2H Odd/Even (own)",
            429 => "Exact 2H Goals",
            430 => "2H 1X2 (own)",
            431 => "2H Double Chance (own)",
            432 => "2H Draw No Bet (own)",
            433 => "2H Both Teams To Score (own)",
            434 => "Both Halves Over 1.5 Yes/No (own)",
            435 => "Both Halves Under 1.5 Yes/No (own)",
            436 => "Home To Score In Both Halves (own)",
            437 => "Away To Score In Both Halves (own)",
            438 => "Home To Win Both Halves (own)",
            439 => "Away To Win Both Halves (own)",
            440 => "Home To Win Either Half (own)",
            441 => "Away To Win Either Half (own)",
            442 => "Highest Scoring Half (own)",
            443 => "Highest Scoring Half Home Team (own)",
            444 => "Highest Scoring Half Away Team (own)",
            445 => "Both Teams To Score In 1H/2H",
            446 => "Home 1H To Score/2H To Score",
            447 => "Away 1H To Score/2H To Score",
            448 => "Last Team To Score",
            449 => "Double Chance/Total Goals",
            450 => "Odd Even/Total Goals",
            451 => "Both Teams to Score/Double Chance",
        ];
    }

    private function betType6()
    {
        return [
            452 => "Highest Scoring Half (2 Way)",
            453 => "1H 3-Way Handicap",
            454 => "Double Chance/First Team To Score",
            455 => "Time of First Goal",
            456 => "1H Both Teams To Score/Result",
            457 => "1H Both Teams To Score/Total Goals",
            458 => "Asian 1X2",
            459 => "1H Asian 1X2",
            460 => "Which Team Will Win By 5+ Goals",
            461 => "Home Team Over/Under (dec)",
            462 => "Away Team Over/Under (dec)",
            463 => "1H Home Team Over/Under (dec)",
            464 => "1H Away Team Over/Under (dec)",
            465 => "Asian 1X2 HDP",
            466 => "1H Asian 1X2 HDP",
            467 => "Half Time/Full Time Exact Total Goals",
            468 => "Score Box Handicap",
            469 => "Score Box Over/Under",
            470 => "Corners Odd/Even (own)",
            471 => "1H Corners Odd/Even (own)",
            472 => "2H Corners Odd/Even",
            473 => "Total Corners",
            474 => "1H Total Corners (own)",
            475 => "Alternative Corners",
            476 => "1H Alternative Corners",
            477 => "Corner 3-Way Handicap",
            478 => "1H Corner 3-Way Handicap",
            479 => "Time Of First Corner",
            481 => "Time Of 2H First Corner",
            482 => "Home Team Over/Under Corners",
            483 => "Away Team Over/Under Corners",
            484 => "1H Home Team Over/Under Corners",
            485 => "1H Away Team Over/Under Corners",
            486 => "Corners Race",
            487 => "1H Corners Race",
            488 => "First Corner (own)",
            489 => "1H First Corner (own)",
            490 => "2H First Corner",
            491 => "Last Corner (own)",
            492 => "1H Last Corner (own)",
            493 => "Half Time/Full Time Total Corners",
            494 => "1H Correct Corners",
            495 => "2H Correct Corners",
            496 => "Corner Highest Scoring Half",
            497 => "Corner Highest Scoring Half (2-Way)",
            500 => "Charge Commission",
            501 => "Match Winner",
            502 => "Match Winner 1X2",
            599 => "Others",
            601 => "Winning Margin 14 Way",
        ];
    }

    private function betType7()
    {
        return [
            602 => "Winning Margin 12 Way",
            603 => "Which Team To Score The Highest Quarter",
            604 => "Which Team To Score The First Basket",
            605 => "Which Team To Score The Last Basket",
            606 => "1H Race To X Points",
            607 => "2H Race To X Points",
            608 => "1H Winning Margin 13 Way",
            609 => "Quarter X Handicap",
            610 => "Quarter X Over/Under",
            611 => "Quarter X Odd/Even",
            612 => "Quarter X Moneyline",
            613 => "Quarter X Race To Y Points",
            614 => "Quarter X Winning Margin 7 Way",
            615 => "Quarter X Home Team Over/Under",
            616 => "Quarter X Away Team Over/Under",
            617 => "Quarter X Which Team To Score The Last Basket",
            618 => "Last Digit Score",
            619 => "Home Team Last Digit Score",
            620 => "Away Team Last Digit Score",
            621 => "1H Last Digit Score",
            622 => "1H Home Team Last Digit Score",
            623 => "1H Away Team Last Digit Score",
            624 => "2H Last Digit Score",
            625 => "2H Home Team Last Digit Score",
            626 => "2H Away Team Last Digit Score",
            627 => "Quarter X Last Digit Score",
            628 => "Quarter X Home Team Last Digit Score",
            629 => "Quarter X Away Team Last Digit Score",
            630 => "Quarter X 1X2",
            631 => "Quarter X Double Chance",
            632 => "Correct Quarter Odd/Even",
            633 => "Quarter 1/Quarter 2 Result",
            634 => "Quarter 3/Quarter 4 Result",
            635 => "Quarter To Win To Nil",
            636 => "Quarter To Win From Behind",
            637 => "Quarters Winners Handicap",
            638 => "Home Team Quarters Win Over/Under",
            639 => "Away Team Quarters Win Over/Under",
            640 => "Exact Quarter Draw",
            641 => "Quarter Draw Over/Under",
            642 => "Double Quarter Winner",
            643 => "Highest Scoring Quarter",
            644 => "Quarter Correct Score",
            645 => "1st Half/2nd Half Result",
            646 => "Match Handicap & Total",
            647 => "Ending Game",
            648 => "1H Ending Game",
            649 => "2H Ending Game",
            650 => "Quarter X Ending Game",
            701 => "Match Handicap",
        ];
    }

    private function betType8()
    {
        return [
            702 => "Match Number of Games",
            703 => "Match Correct Score",
            704 => "Match Points Handicap",
            705 => "Match Points Over/Under",
            706 => "Match Points Odd/Even",
            707 => "Game X Winner",
            708 => "Game X Points Handicap",
            709 => "Game X Points Over/Under",
            710 => "Game X Points Odd/Even",
            711 => "Game X Winning Margin",
            712 => "Game X Race to Y Points",
            713 => "Game X Points Y Winner",
            714 => "Game X Extra Points",
            801 => "Goal Within 60 Seconds",
            802 => "Dynamic Offering",
            803 => "Next Set Piece",
            804 => "Every Single Minute",
            805 => "Time of Possession",
            806 => "First Goal (0-19:59/20-45+/2ndHalf)",
            901 => "Sold",
            902 => "Bought",
            903 => "BetTrade Commission",
            904 => "BetTrade Winloss Sharing",
            911 => "Cash Out",
            912 => "Bought",
            913 => "Cashout Commission",
            914 => "Cashout Winloss Sharing",
            915 => "2-way Market",
            916 => "3-way Market",
            917 => "Others",
            918 => "Parlay & Outright",
            998 => "Parlay Boost Adjustment",
            999 => "Odds Spread Adjustment",
            1000 => "P2P Games",
            1001 => "13 Cards",
            1002 => "Texas Hold'em",
            1003 => "Cockfighting",
            1004 => "Bullfighting",
            1011 => "Fishing World",
            1021 => "Max5D",
            1022 => "Max3D",
            1023 => "Max11x5",
            1024 => "Lottery",
            1031 => "Max5D",
            1032 => "Max5D 90",
            1033 => "Max3D",
            1034 => "Max3D 90",
            1035 => "Max11x5",
            1036 => "Max11x5 90",
            1037 => "MaxDice 2",
        ];
    }

    private function betType9()
    {
        return [
            1038 => "MaxDice",
            1039 => "Max Racing",
            1040 => "Max Racing 2",
            1041 => "Penalty Shoot-out",
            1042 => "Penalty Shoot-out 2",
            1043 => "Se Die",
            1044 => "Se Die 2",
            1045 => "Lottery Bull",
            1046 => "Lottery Bull 2",
            1047 => "Max Se Die",
            1048 => "Max Se Die 2",
            1065 => "Max6",
            1071 => "Jhandi Munda",
            1072 => "Ladder Game",
            1073 => "Fireball 10",
            1074 => "MaxDice 3",
            1075 => "MaxDice 4",
            1076 => "Ladder Game 2",
            1101 => "Premium Baccarat",
            1102 => "Party Roulette",
            1103 => "Live Baccarat",
            1104 => "Live Roulette",
            1106 => "No Card Baccarat",
            1201 => "Handicap",
            1203 => "Over/Under",
            1204 => "Correct Score",
            1205 => "FT.1X2",
            1206 => "Total Goal",
            1220 => "Moneyline",
            1224 => "Double Chance",
            1231 => "Win",
            1232 => "Place",
            1233 => "Win/Place",
            1235 => "Correct Score",
            1236 => "Total Points",
            1237 => "Forecast",
            1238 => "Tri-cast",
            1240 => "Match Betting",
            1241 => "Total 4's",
            1242 => "Total Boundaries",
            1243 => "Both Team to hit a 6",
            1244 => "Total 6's",
            1245 => "Both Teams to hit a 4",
            1246 => "Total Runs Odd/Even",
            1301 => "Match Winner",
            1302 => "Match Correct Score (3rd)",
            1303 => "Set Handicap",
            1304 => "Total Sets",
            1305 => "Match Total Games Odd/Even",
            1306 => "Match Total Games Over/Under",
        ];
    }

    private function betType10()
    {
        return [
            1307 => "Match Total Games 3-way",
            1308 => "Match Games Handicap (3rd)",
            1309 => "Match Handicap Games 3-way",
            1310 => "Player X Match Total Games 2-way",
            1311 => "Set x Winner (3rd)",
            1312 => "Set x Total Games (3rd)",
            1313 => "Set X Total Games 3-way",
            1314 => "Set X Will There Be A Tiebreak?",
            1315 => "Set X Player to win on a Tiebreak?",
            1316 => "Set x Game Handicap (3rd)",
            1317 => "Set x Correct Score",
            1318 => "Set x Total Game  Odd/Even",
            1319 => "Set X Race to Y Games",
            1320 => "Set X Score after 2 Games",
            1321 => "Set X Score after 4 Games",
            1322 => "Set X Score after 6 Games",
            1323 => "Set X Total Deuce Games 2-way",
            1324 => "Set x Game y Winner",
            1325 => "Set X Game Y Correct Score",
            1326 => "Set X Game Y Point Handicap",
            1327 => "Set X Game Y Deuce Betting",
            1328 => "Set X Game Y Total Points Exact",
            1329 => "Set X Game Y Total Points 2-way",
            1330 => "Set X Game Y Total Points 3-way",
            1331 => "Set X Game Y Total Points Odd/Even",
            1332 => "Set X Game Y Point Z Winner",
            1333 => "Set X Games Y & Y+1 Winner",
            1334 => "Set X Games Y & Y+1 Points",
            8700 => "Streamer Tips",
            8800 => "Run Line",
            8801 => "Total Runs",
            8802 => "Home Team Total Runs",
            8803 => "Away Team Total Runs",
            8804 => "First X Innings Moneyline",
            8805 => "First X Innings Result",
            8806 => "First X Innings Run Line",
            8807 => "First X Innings Total Runs",
            8808 => "First X Innings Home Team Total Runs",
            8809 => "First X Innings Away Team Total Runs",
            8810 => "X Inning Result",
            8811 => "X Inning Run Line",
            8812 => "X Inning Total Runs",
            8813 => "X Inning Exact Total Runs",
            8814 => "Both Team To Score X Runs",
            8815 => "Extra Inning Yes/No ",
            8816 => "Total Hits",
            8817 => "Hits Result ",
            8818 => "Team with Highest Inning Score",
            8819 => "Lead After X Innings",
            8820 => "Race To X Runs",
        ];
    }

    private function betType11()
    {
        return [
            8821 => "First Team To Score ",
            8822 => "Winning Margin (Baseball)",
            8823 => "X Inning Hits Handicap",
            8824 => "X Inning Total Hits ",
            8825 => "Moneyline and Total Runs",
            8826 => "Total Runs (Bands)",
            8827 => "Last Team To Score (Baseball)",
            8828 => "To Win Series ",
            8829 => "Series Games Handicap ",
            8830 => "Series Total Games",
            8831 => "Series Correct Score",
            8832 => "Series Leader After Game 3",
            8833 => "Series Leader After Game 4",
            8834 => "Series Correct Score After Game 3",
            8835 => "Series Correct Score After Game 4",
            9001 => "Map X Moneyline",
            9002 => "Map X Total Kills Handicap",
            9003 => "Map X Total Kills Over/Under",
            9004 => "Map X Total Kills Moneyline",
            9005 => "Map X Total Kills Odd/Even",
            9006 => "Map X First Blood",
            9007 => "Map X First to Y Kills",
            9008 => "Map X Total Towers Handicap",
            9009 => "Map X Total Towers Over/Under",
            9010 => "Map X Total Towers Moneyline",
            9011 => "Map X First Tier Y Tower",
            9012 => "Map X Total Roshans Handicap",
            9013 => "Map X Total Roshans Over/Under",
            9014 => "Map X Total Roshans Moneyline",
            9015 => "Map X 1st Roshan",
            9016 => "Map X 2nd Roshan",
            9017 => "Map X 3rd Roshan",
            9018 => "Map X Total Barracks Handicap",
            9019 => "Map X Total Barracks Over/Under",
            9020 => "Map X Total Barracks Moneyline",
            9021 => "Map X 1st Barrack",
            9022 => "Map X 2nd Barrack",
            9023 => "Map X 3rd Barrack",
            9024 => "Map X Total Turrets Handicap",
            9025 => "Map X Total Turrets Over/Under",
            9026 => "Map X Total Turrets Moneyline",
            9027 => "Map X First Tier Y Turret",
            9028 => "Map X Total Dragons Handicap",
            9029 => "Map X Total Dragons Over/Under",
            9030 => "Map X Total Dragons Moneyline",
            9031 => "Map X 1st Dragon",
            9032 => "Map X 2nd Dragon",
            9033 => "Map X 3rd Dragon",
            9034 => "Map X Total Barons Handicap",
            9035 => "Map X Total Barons Over/Under",
        ];
    }

    private function betType12()
    {
        return [
            9036 => "Map X Total Barons Moneyline",
            9037 => "Map X 1st Baron",
            9038 => "Map X 2nd Baron",
            9039 => "Map X 3rd Baron",
            9040 => "Map X Total Inhibitors Handicap",
            9041 => "Map X Total Inhibitors Over/Under",
            9042 => "Map X Total Inhibitors Moneyline",
            9043 => "Map X 1st Inhibitor",
            9044 => "Map X 2nd Inhibitor",
            9045 => "Map X 3rd Inhibitor",
            9046 => "Map X Total Tyrants Handicap",
            9047 => "Map X Total Tyrants Over/Under",
            9048 => "Map X Total Tyrants Moneyline",
            9049 => "Map X 1st Tyrant",
            9050 => "Map X 2nd Tyrant",
            9051 => "Map X 3rd Tyrant",
            9052 => "Map X Total Overlords Handicap",
            9053 => "Map X Total Overlords Over/Under",
            9054 => "Map X Total Overlords Moneyline",
            9055 => "Map X 1st Overlord",
            9056 => "Map X 2nd Overlord",
            9057 => "Map X 3rd Overlord",
            9058 => "Map X Duration Over/Under (Mins)",
            9059 => "Map X Rounds Handicap",
            9060 => "Map X Rounds Over/Under",
            9061 => "Map X Rounds Odd/Even",
            9062 => "Map X First to Y Rounds",
            9063 => "Map X First Half",
            9064 => "Map X Second Half",
            9065 => "Map X Most First Kill",
            9066 => "Map X Clutches",
            9067 => "Map X 16th Round",
            9068 => "Map X Round Y Moneyline",
            9069 => "Map X Round Y Total Kills Moneyline",
            9070 => "Map X Round Y Total Kills Over/Under",
            9071 => "Map X Round Y Total Kills Odd/Even",
            9072 => "Map X Round Y First Kill",
            9073 => "Map X Round Y Bomb Plant",
            9074 => "Map X Overtime - Yes/No",
            9075 => "Map X Final Round Bomb Plant",
            9076 => "Map X Clutches Handicap",
            9077 => "Map X Round Y Total Kills Handicap",
            9078 => "Map X Total Towers Odd/Even",
            9079 => "Map X Total Roshans Odd/Even",
            9080 => "Map X Total Barracks Odd/Even",
            9081 => "Map X Total Turrets Odd/Even",
            9082 => "Map X Total Dragons Odd/Even",
            9083 => "Map X Total Barons Odd/Even",
            9084 => "Map X Total Inhibitors Odd/Even",
            9085 => "Map X Total Tyrants Odd/Even",
        ];
    }

    private function betType13()
    {
        return [
            9086 => "Map X Total Overlords Odd/Even",
            9087 => "Map X Overtime",
            9088 => "Correct Map Score",
            9089 => "Map X First to Y Kills Time(Mins) Over/Under",
            9090 => "Map X First Blood Time(Mins) Over/Under",
            9091 => "Map X Total Kills at 10 Mins Handicap",
            9092 => "Map X Total Kills at 10 Mins Over/Under",
            9093 => "Map X Total Kills at 20 Mins Handicap",
            9094 => "Map X Total Kills at 20 Mins Over/Under",
            9095 => "Map X Home Team Total Kills at 10 Mins Over/Under",
            9096 => "Map X Away Team Total Kills at 10 Mins Over/Under",
            9097 => "Map X Home Team Total Kills at 20 Mins Over/Under",
            9098 => "Map X Away Team Total Kills at 20 Mins Over/Under",
            9099 => "Map X Home Team Total Kills Over/Under",
            9100 => "Map X Away Team Total Kills Over/Under",
            9101 => "Map X 1st Kill",
            9102 => "Map X 2nd Kill",
            9103 => "Map X 3rd Kill",
            9104 => "Map X 4th Kill",
            9105 => "Map X 5th Kill",
            9106 => "Map X 6th Kill",
            9107 => "Map X 7th Kill",
            9108 => "Map X 8th Kill",
            9109 => "Map X 9th Kill",
            9110 => "Map X 10th Kill",
            9111 => "Map X 15th Kill",
            9112 => "Map X 20th Kill",
            9113 => "Map X Lane With Most Turrets Destroyed",
            9114 => "Map X First Turret Location",
            9115 => "Map X Total Gold Moneyline",
            9116 => "Map X Total Gold(In Thousands) Handicap",
            9117 => "Map X Total Gold(In Thousands) Over/Under",
            9118 => "Map X Home Team Total Gold(In Thousands) Over/Under",
            9119 => "Map X Away Team Total Gold(In Thousands) Over/Under",
            9120 => "Map X Total Gold Odd/Even",
            9121 => "Map X First Tyrant Time(Mins) Over/Under",
            9122 => "Map X First Dark Tyrant",
            9123 => "Map X First Overlord Time(Mins) Over/Under",
            9124 => "Map X Will Storm Dragon Be Killed Yes/No",
            9125 => "Map X First Herald",
            9126 => "Map X First Herald Time(Mins) Over/Under",
            9127 => "Map X First Baron Time(Mins) Over/Under",
            9128 => "Map X First Baron No. Players Buff Over/Under",
            9129 => "Map X First Inhibitor Time(Mins) Over/Under",
            9130 => "Map X First Inhibitor Location",
            9131 => "Map X First Dragon Time(Mins) Over/Under",
            9132 => "Map X Will Elder Dragon Be Killed Yes/No",
            9133 => "Map X Will Any Aegis Be Snatched Yes/No",
            9134 => "Map X First Tower Time(Mins) Over/Under",
            9135 => "Map X First Tower Location",
        ];
    }

    private function betType14()
    {
        return [
            9136 => "Map X First Roshan Time(Mins) Over/Under",
            9137 => "Map X First Barrack Time(Mins) Over/Under",
            9138 => "Map X First Barrack Location",
            9139 => "Map X Total Bomb Detonations Over/Under (Excl. OT)",
            9140 => "Map X Total Bomb Defuses Over/Under (Excl. OT)",
            9141 => "Map X Lane With Most Turrets Destroyed (KOG)",
            9142 => "Map X First Turret Location (KOG)",
            9400 => "Super Over Winner",
            9401 => "Toss Winner",
            9402 => "Winning Margin Runs Handicap",
            9403 => "Winning Margin Wickets Handicap",
            9404 => "Home Inns Runs",
            9405 => "Away Inns Runs",
            9406 => "Home 1st Inns Runs",
            9407 => "Away 1st Inns Runs",
            9408 => "Home 2nd Inns Runs",
            9409 => "Away 2nd Inns Runs",
            9410 => "Home Group 1-X Runs",
            9411 => "Away Group 1-X Runs",
            9412 => "Home 1st Inns Group 1-X Runs",
            9413 => "Away 1st Inns Group 1-X Runs",
            9414 => "Home 2nd Inns Group 1-X Runs",
            9415 => "Away 2nd Inns Group 1-X Runs",
            9416 => "Home Score at End of Over X",
            9417 => "Away Score at End of Over X",
            9418 => "Home 1st Inns Score at End of Over X",
            9419 => "Away 1st Inns Score at End of Over X",
            9420 => "Home 2nd Inns Score at End of Over X",
            9421 => "Away 2nd Inns Score at End of Over X",
            9422 => "Home Score after Over X Ball Y",
            9423 => "Away Score after Over X Ball Y",
            9424 => "Home 1st Inns Score after Over X Ball Y",
            9425 => "Away 1st Inns Score after Over X Ball Y",
            9426 => "Home 2nd Inns Score after Over X Ball Y",
            9427 => "Away 2nd Inns Score after Over X Ball Y",
            9428 => "Home Fall of Wicket X",
            9429 => "Away Fall of Wicket X",
            9430 => "Home 1st Inns Fall of Wicket X",
            9431 => "Away 1st Inns Fall of Wicket X",
            9432 => "Home 2nd Inns Fall of Wicket X",
            9433 => "Away 2nd Inns Fall of Wicket X",
            9434 => "Home Wicket X Method of Dismissal",
            9435 => "Away Wicket X Method of Dismissal",
            9436 => "Home 1st Inns Wicket X Method of Dismissal",
            9437 => "Away 1st Inns Wicket X Method of Dismissal",
            9438 => "Home 2nd Inns Wicket X Method of Dismissal",
            9439 => "Away 2nd Inns Wicket X Method of Dismissal",
            9440 => "Most Fours",
            9441 => "Most Sixes",
            9442 => "Highest Opening Partnership",
        ];
    }

    private function betType15()
    {
        return [
            9443 => "Highest Score in Over 1",
            9444 => "Highest Score in Group 1-X",
            9445 => "Match Runs",
            9446 => "Match Fours",
            9447 => "Match Sixes",
            9448 => "Match Run Outs",
            9449 => "Match Wickets",
            9450 => "Match Extras",
            9451 => "Match Dot Balls",
            9452 => "Highest Individual Score",
            9453 => "Highest Over Score",
            9454 => "Home Inns Fours",
            9455 => "Away Inns Fours",
            9456 => "Home 1st Inns Fours",
            9457 => "Away 1st Inns Fours",
            9458 => "Home 2nd Inns Fours",
            9459 => "Away 2nd Inns Fours",
            9460 => "Home Inns Sixes",
            9461 => "Away Inns Sixes",
            9462 => "Home 1st Inns Sixes",
            9463 => "Away 1st Inns Sixes",
            9464 => "Home 2nd Inns Sixes",
            9465 => "Away 2nd Inns Sixes",
            9466 => "Home Inns Run Outs",
            9467 => "Away Inns Run Outs",
            9468 => "Home 1st Inns Run Outs",
            9469 => "Away 1st Inns Run Out",
            9470 => "Home 2nd Inns Run Outs",
            9471 => "Away 2nd Inns Run Out",
            9472 => "Home Inns Wickets",
            9473 => "Away Inns Wickets",
            9474 => "Home 1st Inns Wickets",
            9475 => "Away 1st Inns Wickets",
            9476 => "Home 2nd Inns Wickets",
            9477 => "Away 2nd Inns Wickets",
            9478 => "Home Inns Extras",
            9479 => "Away Inns Extras",
            9480 => "Home 1st Inns Extras",
            9481 => "Away 1st Inns Extras",
            9482 => "Home 2nd Inns Extras",
            9483 => "Away 2nd Inns Extras",
            9484 => "Home Over X Exact Runs",
            9485 => "Away Over X Exact Runs",
            9486 => "Home 1st Inns Over X Exact Runs",
            9487 => "Away 1st Inns Over X Exact Runs",
            9488 => "Home 2nd Inns Over X Exact Runs",
            9489 => "Away 2nd Inns Over X Exact Runs",
            9490 => "Home Over X Ball Y Exact Runs",
            9491 => "Away Over X Ball Y Exact Runs",
            9492 => "Home 1st Inns Over X Ball Y Exact Runs",
        ];
    }

    private function betType16()
    {
        return [
            9493 => "Away 1st Inns Over X Ball Y Exact Runs",
            9494 => "Home 2nd Inns Over X Ball Y Exact Runs",
            9495 => "Away 2nd Inns Over X Ball Y Exact Runs",
            9496 => "Home Inns Runs OE",
            9497 => "Away Inns Runs OE",
            9498 => "Home 1st Inns Runs OE",
            9499 => "Away 1st Inns Runs OE",
            9500 => "Home 2nd Inns Runs OE",
            9501 => "Away 2nd Inns Runs OE",
            9502 => "Home Group 1-X Runs OE",
            9503 => "Away Group 1-X Runs OE",
            9504 => "Home 1st Inns Group 1-X Runs OE",
            9505 => "Away 1st Inns Group 1-X Runs OE",
            9506 => "Home 2nd Inns Group 1-X Runs OE",
            9507 => "Away 2nd Inns Group 1-X Runs OE",
            9508 => "Home Score at End of Over X OE",
            9509 => "Away Score at End of Over X OE",
            9510 => "Home 1st Inns Score at End of Over X OE",
            9511 => "Away 1st Inns Score at End of Over X OE",
            9512 => "Home 2nd Inns Score at End of Over X OE",
            9513 => "Away 2nd Inns Score at End of Over X OE",
            9514 => "Home Fall of Wicket X OE",
            9515 => "Away Fall of Wicket X OE",
            9516 => "Home 1st Inns Fall of Wicket X OE",
            9517 => "Away 1st Inns Fall of Wicket X OE",
            9518 => "Home 2nd Inns Fall of Wicket X OE",
            9519 => "Away 2nd Inns Fall of Wicket X OE",
            9520 => "Most Fours HDP",
            9521 => "Most Sixes HDP",
            9522 => "Handicap (Dec)",
            9523 => "Highest Opening Partnership HDP",
            9524 => "Highest Score in Over 1 HDP",
            9525 => "Highest Score in Group 1-X HDP",
            9526 => "Match Runs OE",
            9527 => "Match Fours OE",
            9528 => "Match Sixes OE",
            9529 => "Match Run Outs OE",
            9530 => "Match Extras OE",
            9531 => "Match Dot Balls OE",
            9532 => "Home Inns Fours OE",
            9533 => "Away Inns Fours OE",
            9534 => "Home 1st Inns Fours OE",
            9535 => "Away 1st Inns Fours OE",
            9536 => "Home 2nd Inns Fours OE",
            9537 => "Away 2nd Inns Fours OE",
            9538 => "1X2 (Back & Lay)",
            9539 => "Match Winner (Back & Lay)",
            9540 => "Super Over Winner (Back & Lay)",
            9541 => "Home Inns Runs Fancy",
            9542 => "Away Inns Runs Fancy",
        ];
    }

    private function betType17()
    {
        return [
            9543 => "Home 1st Inns Runs Fancy",
            9544 => "Away 1st Inns Runs Fancy",
            9545 => "Home 2nd Inns Runs Fancy",
            9546 => "Away 2nd Inns Runs Fancy",
            9547 => "Home Group 1-X Runs Fancy",
            9548 => "Away Group 1-X Runs Fancy",
            9549 => "Home 1st Inns Group 1-X Runs Fancy",
            9550 => "Away 1st Inns Group 1-X Runs Fancy",
            9551 => "Home 2nd Inns Group 1-X Runs Fancy",
            9552 => "Away 2nd Inns Group 1-X Runs Fancy",
            9553 => "Home Score at End of Over X Fancy",
            9554 => "Away Score at End of Over X Fancy",
            9555 => "Home 1st Inns Score at End of Over X Fancy",
            9556 => "Away 1st Inns Score at End of Over X Fancy",
            9557 => "Home 2nd Inns Score at End of Over X Fancy",
            9558 => "Away 2nd Inns Score at End of Over X Fancy",
            9559 => "Home Fall of Wicket X Fancy",
            9560 => "Away Fall of Wicket X Fancy",
            9561 => "Home 1st Inns Fall of Wicket X Fancy",
            9562 => "Away 1st Inns Fall of Wicket X Fancy",
            9563 => "Home 2nd Inns Fall of Wicket X Fancy",
            9564 => "Away 2nd Inns Fall of Wicket X Fancy",
            9565 => "Match Runs Fancy",
            9566 => "Match Fours Fancy",
            9567 => "Match Sixes Fancy",
            9568 => "Match Run Outs Fancy",
            9569 => "Match Wickets Fancy",
            9570 => "Match Extras Fancy",
            9571 => "Match Dot Balls Fancy",
            9572 => "Highest Individual Score Fancy",
            9573 => "Highest Over Score Fancy",
            9574 => "Home Inns Fours Fancy",
            9575 => "Away Inns Fours Fancy",
            9576 => "Home 1st Inns Fours Fancy",
            9577 => "Away 1st Inns Fours Fancy",
            9578 => "Home 2nd Inns Fours Fancy",
            9579 => "Away 2nd Inns Fours Fancy",
            9580 => "Home Inns Sixes Fancy",
            9581 => "Away Inns Sixes Fancy",
            9582 => "Home 1st Inns Sixes Fancy",
            9583 => "Away 1st Inns Sixes Fancy",
            9584 => "Home 2nd Inns Sixes Fancy",
            9585 => "Away 2nd Inns Sixes Fancy",
            9586 => "Home Inns Run Outs Fancy",
            9587 => "Away Inns Run Outs Fancy",
            9588 => "Home 1st Inns Run Outs Fancy",
            9589 => "Away 1st Inns Run Out Fancy",
            9590 => "Home 2nd Inns Run Outs Fancy",
            9591 => "Away 2nd Inns Run Out Fancy",
            9592 => "Home Inns Wickets Fancy",
        ];
    }

    private function betType18()
    {
        return [
            9593 => "Away Inns Wickets Fancy",
            9594 => "Home 1st Inns Wickets Fancy",
            9595 => "Away 1st Inns Wickets Fancy",
            9596 => "Home 2nd Inns Wickets Fancy",
            9597 => "Away 2nd Inns Wickets Fancy",
            9598 => "Home Inns Extras Fancy",
            9599 => "Away Inns Extras Fancy",
            9600 => "Home 1st Inns Extras Fancy",
            9601 => "Away 1st Inns Extras Fancy",
            9602 => "Home 2nd Inns Extras Fancy",
            9603 => "Away 2nd Inns Extras Fancy",
            9604 => "Over/Under (dec)",
            9605 => "Odd/Even (dec)",
            9606 => "Fancy",
            9607 => "Home Over X Runs",
            9608 => "Away Over X Runs",
            9609 => "Home 1st Inns Over X Runs",
            9610 => "Away 1st Inns Over X Runs",
            9611 => "Home 2nd Inns Over X Runs",
            9612 => "Away 2nd Inns Over X Runs",
            9613 => "Home Over X Ball Y Runs",
            9614 => "Away Over X Ball Y Runs",
            9615 => "Most Run Outs",
            9616 => "Home Over X Delivery Y Runs",
            9617 => "Away Over X Delivery Y Runs",
            9618 => "Home Over X Runs OE",
            9619 => "Away Over X Runs OE",
            9620 => "Home 1st Inns Over X Runs OE",
            9621 => "Away 1st Inns Over X Runs OE",
            9622 => "Home 2nd Inns Over X Runs OE",
            9623 => "Away 2nd Inns Over X Runs OE",
            9624 => "Will there be a Boundary Fours in Home Over X?",
            9625 => "Will there be a Boundary Fours in Away Over X?",
            9626 => "Will there be a Boundary Fours in Home 1st Inns Over X?",
            9627 => "Will there be a Boundary Fours in Away 1st Inns Over X?",
            9628 => "Will there be a Boundary Fours in Home 2nd Inns Over X?",
            9629 => "Will there be a Boundary Fours in Away 2nd Inns Over X?",
            9630 => "Will there be a Boundary Sixes in Home Over X?",
            9631 => "Will there be a Boundary Sixes in Away Over X?",
            9632 => "Will there be a Boundary Sixes in Home 1st Inns Over X?",
            9633 => "Will there be a Boundary Sixes in Away 1st Inns Over X?",
            9634 => "Will there be a Boundary Sixes in Home 2nd Inns Over X?",
            9635 => "Will there be a Boundary Sixes in Away 2nd Inns Over X?",
            9636 => "Home Wicket X Method of Dismissal (6 Way)",
            9637 => "Away Wicket X Method of Dismissal (6 Way)",
            9638 => "Home 1st Inns Wicket X Method of Dismissal (6 Way)",
            9639 => "Away 1st Inns Wicket X Method of Dismissal (6 Way)",
            9640 => "Home 2nd Inns Wicket X Method of Dismissal (6 Way)",
            9641 => "Away 2nd Inns Wicket X Method of Dismissal (6 Way)",
            9650 => "Home Top Batsman",
        ];
    }

    private function betType19()
    {
        return [
            9651 => "Away Top Batsman",
            9652 => "Home 1st Inns Top Batsman",
            9653 => "Away 1st Inns Top Batsman",
            9654 => "Home 2nd Inns Top Batsman",
            9655 => "Away 2nd Inns Top Batsman",
            9656 => "Home Top Bowler",
            9657 => "Away Top Bowler",
            9658 => "Home 1st Inns Top Bowler",
            9659 => "Away 1st Inns Top Bowler",
            9660 => "Home 2nd Inns Top Bowler",
            9661 => "Away 2nd Inns Top Bowler",
            9662 => "Home Next Man Out",
            9663 => "Away Next Man Out",
            9664 => "Home 1st Inns Next Man Out",
            9665 => "Away 1st Inns Next Man Out",
            9666 => "Home 2nd Inns Next Man Out",
            9667 => "Away 2nd Inns Next Man Out",
            9668 => "Home Prematch Top Batsman",
            9669 => "Away Prematch Top Batsman",
            9670 => "Home 1st Inns Prematch Top Batsman",
            9671 => "Away 1st Inns Prematch Top Batsman",
            9672 => "Home Prematch Top Bowler",
            9673 => "Away Prematch Top Bowler",
            9674 => "Home 1st Inns Prematch Top Bowler",
            9675 => "Away 1st Inns Prematch Top Bowler",
            9676 => "Home Player Runs",
            9677 => "Home Player Runs OE",
            9678 => "Home 1st Inns Player Runs",
            9679 => "Home 1st Inns Player Runs OE",
            9680 => "Home Batsman Runs",
            9681 => "Home Batsman Runs OE",
            9682 => "Home 1st Inns Batsman Runs",
            9683 => "Home 1st Inns Batsman Runs OE",
            9684 => "Home 2nd Inns Batsman Runs",
            9685 => "Home 2nd Inns Batsman Runs OE",
            9686 => "Away Player Runs",
            9687 => "Away Player Runs OE",
            9688 => "Away 1st Inns Player Runs",
            9689 => "Away 1st Inns Player Runs OE",
            9690 => "Away Batsman Runs",
            9691 => "Away Batsman Runs OE",
            9692 => "Away 1st Inns Batsman Runs",
            9693 => "Away 1st Inns Batsman Runs OE",
            9694 => "Away 2nd Inns Batsman Runs",
            9695 => "Away 2nd Inns Batsman Runs OE",
            9696 => "Home 2nd Inns Batsman Fours",
            9697 => "Away 2nd Inns Batsman Fours",
            9698 => "Home Batsman Milestones",
            9699 => "Away Batsman Milestones",
            9702 => "Home 1st Inns Batsman Milestones",
        ];
    }

    private function betType20()
    {
        return [
            9703 => "Away 1st Inns Batsman Milestones",
            9704 => "Home 2nd Inns Batsman Milestones",
            9705 => "Away 2nd Inns Batsman Milestones",
            9708 => "1st Inns Highest Individual Score",
            9709 => "1st Inns Highest Over Score",
            9710 => "1st Inns Highest Opening Partnership",
            9711 => "1st Inns Highest Score in Over 1",
            9712 => "Home Player Runs Fancy",
            9713 => "Home 1st Inns Player Runs Fancy",
            9714 => "Home Batsman Runs Fancy",
            9715 => "Home 1st Inns Batsman Runs Fancy",
            9716 => "Home 2nd Inns Batsman Runs Fancy",
            9717 => "Away Player Runs Fancy",
            9718 => "Away 1st Inns Player Runs Fancy",
            9719 => "Away Batsman Runs Fancy",
            9720 => "Away 1st Inns Batsman Runs Fancy",
            9721 => "Away 2nd Inns Batsman Runs Fancy",
            9722 => "Home Over X Runs Fancy",
            9723 => "Away Over X Runs Fancy",
            9724 => "Home 1st Inns Over X Runs Fancy",
            9725 => "Away 1st Inns Over X Runs Fancy",
            9726 => "Home 2nd Inns Over X Runs Fancy",
            9727 => "Away 2nd Inns Over X Runs Fancy",
            9728 => "1st Inns Highest Over Score Fancy",
            9729 => "1st Inns Highest Individual Score Fancy",
            9730 => "Home Batsman Sixes",
            9731 => "Away Batsman Sixes",
            9732 => "Home 1st Inns Batsman Sixes",
            9733 => "Away 1st Inns Batsman Sixes",
            9734 => "Home 2nd Inns Batsman Sixes",
            9735 => "Away 2nd Inns Batsman Sixes",
            9736 => "Home Batsman Fours",
            9737 => "Away Batsman Fours",
            9738 => "Home 1st Inns Batsman Fours",
            9739 => "Away 1st Inns Batsman Fours",
            "Mix Parlay" => "Mix Parlay",
        ];
    }
}
