<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Http;
use Laravel\Lumen\Routing\Controller;

class SabStgController extends Controller
{
    public function migrate()
    {
        $pos = 30; // not sure

        // foreach ($response['game_list'][213] as $game) {

        // if ($game['is_enabled'] == 0) continue;

        foreach ($this->marketType() as $marketType) {
            $requestData[] = [
                'providerCode' => 'SAB',
                'providerName' => 'SAB Sportsbook',
                'gameCode' => $marketType,
                'gameName' => $marketType,
                'position' => $pos,
                'type' => $marketType,
                'rtp' => '0',
                'imageUrl' => '-',
                'imageAlt' => $marketType,
            ];

            $pos++;
        }

        // dd($requestData);
        // }

        foreach ($requestData as $data) {
            $response = Http::withHeaders([
                'Authorization' => 'Bearer ' . env('BEARER_TOKEN_STG')
                // ])->post(env('dummyAPI'), $data);
            ])->post(env('ADD_GAME_API_STG'), $data);

            Log::info(json_encode([
                'request' => $data,
                'response' => $response->body()
            ]));
        }
    }

    private function marketType()
    {
        return [
            'Handicap',
            'Odd/Even',
            'Over/Under',
            'Correct Score',
            'FT.1X2',
            'Total Goal',
            '1H Handicap',
            '1H Over/Under',
            'Outright',
            'Total Corners',
            '1H Odd/Even',
            'Clean Sheet',
            'First Goal/Last Goal',
            '1H 1X2',
            'HT/FT',
            '2H Handicap',
            '2H Over/Under',
            'Moneyline',
            '1H Moneyline',
            'Next Goal',
            'Double Chance',
            'Draw No Bet',
            'Both/One/Neither Team To Score',
            'To Win To Nil',
            '3-Way Handicap',
            'System Parlay',
            'Single Match Parlay',
        ];



        // return [
        //     '1H Correct Score',
        //     'Next Over/Under (Number Game)',
        //     'Next Odd/Even (Number Game)',
        //     'Next Combo (Number Game)',
        //     'Number wheel (Number Game)',
        //     'Next R/B',
        //     'Home No Be',
        //     'Away No Bet',
        //     'Draw/ No Draw',
        //     'FT.1X2 HDP',
        //     '1H 1X2 HDP',
        //     '1H Total Goal',
        //     '1H First Goal/Last Goal',
        //     'HT/FT Odd/Even',
        //     'Home To Win Both Halves ',
        //     'Away To Win Both Halves',
        //     'Penalty Shootout',
        //     'Highest Scoring Half',
        //     'Highest Scoring Half Home Team',
        //     'Highest Scoring Half Away Team',
        //     'Both Teams To Score',
        //     '2H Both Teams To Score',
        //     'Home To Score In Both Halves',
        //     'Away To Score In Both Halves',
        //     'Home To Win Either Half',
        //     'Away To Win Either Hal',
        //     '1H Double Chance',
        //     'Half Time/Full Time Correct Score',
        //     'Handicap (Virtual Soccer)',
        //     'Over/Under 2.5 Goals (Virtual Soccer)',
        //     'Correct Score (Virtual Soccer)',
        //     '1X2 (Virtual Soccer)',
        //     'Total Goal (Virtual Soccer)',
        //     'Moneyline (Virtual Tennis)',
        //     'Double Chance (Virtual Soccer)',
        //     'Correct Score (Virtual Tennis)',
        //     'Total Points (Virtual Tennis)',
        //     'Game HDP',
        //     'Set x Winner',
        //     'Set x Game Handicap',
        //     'Set x Total Game Over/Under',
        //     'Match Winner',
        //     'Match Correct Score',
        //     'Set Handicap',
        //     'Match Total Games Odd/Even',
        //     'Match Total Games Over/under',
        //     'Match Games Handicap',
        //     'Set x Winner',
        //     'Set x Total Games',
        //     'Set x Game Handicap',
        //     'Set x Correct Score',
        //     'Set x Total Game Odd/Even',
        //     'Set x Game y Winner',
        //     'Odd/Even',
        //     'Exact Total Goals',
        //     'Exact Home Team Goals',
        //     'Exact Away Team Goals',
        //     'Result/Total Goals',
        //     'Extra Time Next Goal',
        //     'Extra Time 1H Correct Score',
        //     'Extra Time Correct Score',
        //     'Extra Time 1H 1X2',
        //     'Who Advances To Next Round',
        //     'Next Goal Time',
        //     'Teams To Score',
        //     'Winning Margin',
        //     'Result And First Team To Score',
        //     'Extra Time Yes/No',
        //     'Extra Time And Goal',
        //     'Match Decided Method',
        //     'First Ten Minutes 1X2',
        //     '2H 1x2',
        //     '2H Over/Under',
        //     'Exact 1H Goals',
        //     '1H Next Goal',
        //     '1H Exact Home Team Goals',
        //     '1H Exact Away Team Goals',
        //     '2H Odd/Even',
        //     '2H Draw No Bet',
        //     '2H Double Chance',
        //     'Exact 2H Goals',
        //     '1H Both Teams To Score',
        //     'Both Halves Over 1.5 Yes/No',
        //     'Both Halves Under 1.5 Yes/No',
        //     '1H Draw No Bet',
        //     'First Goal Specific Time (10 min)',
        //     'First Goal Specific Time (15 min)',
        //     'Corners Odd/Even',
        //     'Home Team Exact Corners',
        //     'Away Team Exact Corners',
        //     'Home Team Total Corners Over/Under',
        //     'Away Team Total Corners Over/Under',
        //     '1H Home Team Exact Corners',
        //     '1H Away Team Exact Corners',
        //     '1H Total Corners',
        //     '1H Corners Odd/Even',
        //     '1H Home Corner Over/Under',
        //     '1H Away Corner Over/Under',
        //     'First Corner',
        //     '1H First Corner',
        //     'Last Corner',
        //     '1H Last Corner',
        //     'Player Sent Off',
        //     '1H Player Sent off',
        //     'Home Team Player Sent Off',
        //     '1H Home Team Player Sent Off',
        //     'Away Team Player Sent Off',
        //     '1H Away Team Player Sent Of',
        //     'Next 1 Minute',
        //     'Next 5 Minutes ',
        //     'What will happen first in next 1 minute',
        //     'What will happen first in next 5 minutes',
        //     'Next 1 minute set piece',
        //     'Which combination will happen first in next 1 min',
        //     'Which combination will happen first in next 5 mins',
        //     'SABA OU Time Machine',
        //     'SABA HDP Time Machine',
        //     'Match Winner',
        //     'Home Team Over/Under',
        //     'Away Team Over/Under',
        //     '1H Home Team Over/Under',
        //     '1H Away Team Over/Under',
        //     '2H Correct Score',
        //     'Exact 1H Goals',
        //     'FT Correct Score',
        //     '1H Correct Score',
        //     'Both Teams To Score/Result',
        //     'Both Teams To Score/Total Goals',
        //     'Which Half First Goal',
        //     'Home Team Which Half First Goal',
        //     'Away Team Which Half First Goal',
        //     'First Team 2 Goals',
        //     'First Team 3 Goals',
        //     'First Goal Method',
        //     'To Win From Behind',
        //     '1H Winning Margin',
        //     'Exact 2H Goals',
        //     'Both Teams To Score In 1H/2H',
        //     'Home 1H to Score/2H To Score',
        //     'Away 1H to Score/2H To Score',
        //     'Winning Margin 14 Way',
        //     'Winning Margin 12 Way',
        //     'Which Team To Score The Highest Quarter',
        //     'Which Team To Score The First Basket',
        //     'Which Team To Score The Last Basket',
        //     '1H Race To X Points',
        //     '2H Race To X Points',
        //     '1H Winning Margin 13 Way',
        //     'Quarter X Handicap',
        //     'Quarter X Over Under',
        //     'Quarter X Odd Even',
        //     'Quarter X Moneyline',
        //     'Quarter X Race To Y Points',
        //     'Quarter X Winning Margin 7 Way',
        //     'Quarter X Home Team Over/Under',
        //     'Quarter X Away Team Over/Under',
        //     'Quarter X Which Team To Score The Last Basket',
        //     'Last Digit Score',
        //     'Home Team Last Digit Score',
        //     'Away Team Last Digit Score',
        //     '1H Last Digit Score',
        //     '1H Home Team Last Digit Score',
        //     '1H Away Team Last Digit Score',
        //     '2H Last Digit Score',
        //     '2H Home Team Last Digit Score',
        //     '2H Away Team Last Digit Score',
        //     'Quarter X Last Digit Score',
        //     'Quarter X Home Team Last Digit Score',
        //     'Quarter X Away Team Last Digit Score',
        //     'Quarter X 1X2',
        //     'Quarter X Double Chance',
        //     'Correct Quarter Odd/Even',
        //     'Quarter 1/Quarter 2 Result',
        //     'Quarter 3/Quarter 4 Result',
        //     'Quarter To Win To Nil',
        //     'Quarter To Win From Behind',
        //     'Quarters Winners Handicap',
        //     'Home Team Quarters Win Over/Under',
        //     'Away Team Quarters Win Over/Under',
        //     'Exact Quarter Draw',
        //     'Quarter Draw Over/Under',
        //     'Double Quarter Winne',
        //     'Highest Scoring Quarter',
        //     'Quarter Correct Score',
        //     '1st Half/2nd Half Result',
        //     'Match Handicap & Total',
        //     'Last Team To Score',
        //     'Double Chance/Total Goals',
        //     'Odd Even/Total Goals',
        //     'Both Teams to Score / Double Chance',
        //     'Highest Scoring Half (2 Way)',
        //     '1H 3-Way Handicap',
        //     'Double Chance/First Team To Score',
        //     'Time of First Goal',
        //     '1H Both Teams To Score / Result',
        //     '1H Both Teams To Score / Total Goals',
        //     'Asian 1X2',
        //     '1H Asian 1X2',
        //     'Which Team Will Win By 5+ Goals',
        //     '1H Result/Total Goals',
        //     '1H Winner',
        //     'Winning Margin 6 Way',
        //     '1H Winning Margin 7 Way',
        //     'FT Race To X Points',
        //     'Map X Moneyline',
        //     'Map X Total Kills Handicap',
        //     'Map X Total Kills Over/Under',
        //     'Map X Total Kills Moneyline',
        //     'Map X Total Kills Odd/Even',
        //     'Map X First Blood',
        //     'Map X First to Y Kills',
        //     'Map X Total Towers Handicap',
        //     'Map X Total Towers Over/Under',
        //     'Map X Total Towers Moneyline',
        //     'Map X First Tier Y Tower',
        //     'Map X Total Roshans Handicap',
        //     'Map X Total Roshans Over/Under',
        //     'Map X Total Roshans Moneyline',
        //     'Map X 1st Roshan',
        //     'Map X 2nd Roshan',
        //     'Map X 3rd Roshan',
        //     'Map X Total Barracks Handicap',
        //     'Map X Total Barracks Over/Under',
        //     'Map X Total Barracks Moneyline',
        //     'Map X 1st Barrack',
        //     'Map X Total Turrets Handicap',
        //     'Map X Total Turrets Over/Under',
        //     'Map X Total Turrets Moneyline',
        //     'Map X First Tier Y Turret',
        //     'Map X Total Dragons Handicap',
        //     'Map X Total Dragons Over/Under',
        //     'Map X Total Dragons Moneyline',
        //     'Map X 1st Dragon',
        //     'Map X 2nd Dragon',
        //     'Map X 3rd Dragon',
        //     'Map X Total Barons Handicap',
        //     'Map X Total Barons Over/Under',
        //     'Map X Total Barons Moneyline',
        //     'Map X 1st Baron',
        //     'Map X 2nd Baron',
        //     'Map X 3rd Baron',
        //     'Map X Total Inhibitors Handicap',
        //     'Map X Total Inhibitors Over/Under',
        //     'Map X Total Inhibitors Moneyline',
        //     'Map X 1st Inhibitor',
        //     'Map X 2nd Inhibitor',
        //     'Map X 3rd Inhibitor',
        //     'Map X Total Tyrants Handicap',
        //     'Map X Total Tyrants Over/Under',
        //     'Map X Total Tyrants Moneyline',
        //     'Map X 1st Tyrant',
        //     'Map X 2nd Tyrant',
        //     'Map X 3rd Tyrant',
        //     'Map X Total Overlords Handicap',
        //     'Map X Total Overlords Over/Under'
        // ];
    
    }
}
